#include"HTMLFunctions.h"

#include <fstream>
namespace Codebook {

using namespace std;

bool saveStringAsHtmlFile(const std::string &str, const std::string &filename) {

  ofstream os(filename.c_str());
  if(!os.is_open())
    return(false);

  os << "<html>\n<head>\n";
  os << "<title>Generated by saveStringAsHtml()</title>\n";
  os << "</head>\n\n";
  os << "<body>\n";
  os << str;
  os << "</body>\n\n</html>";

  os.close();
  return(true);
}


}; // namespace Codebook
